language: go

go:
  - 1.7
  - tip

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.3"

before_install:
  - go get github.com/docker/distribution
  - cd $GOPATH/src/github.com/docker/distribution && git checkout v2.5.0-rc.1; cd $TRAVIS_BUILD_DIR

before_script:
  - psql -c 'create database distribution;' -U postgres

script:
  - go test -test.v -test.short -coverprofile=coverage.txt -covermode=atomic ./pgdriver

after_success:
  - bash <(curl -s https://codecov.io/bash)
